### ISSUE TITLE
Not working with Companion v1.4.0 on windows

### ISSUE THREAD

**Issue by kutuz00** [bitfocus/companion-module-hologfx-holographics#2]
instance(hologfx-holographics): Configured instance hologfx-holographics could not be loaded, unknown module

this is an error message I getting

**Comment by florisporro** [comment]
Are you using the official companion-1.4.0-b402e70 from the website?

**Comment by kutuz00** [comment]
Yes.  Downloaded from their website directly 

Tested on MacOS: no issue
Win10 error

**Comment by florisporro** [comment]
It appears that, for windows builds on 1.4, an older version of this module was used, so there is currently no windows version available on 1.4. Best option is to use any of the latest 2.0 experimental builds, where @JeffreyDavidsz has just upgraded the module to the latest version.
